### ISSUE TITLE
Create a GitHub Actions workflow

### ISSUE THREAD

**Issue by yutna** [datawowio/nextjs-template#15]
Create a GitHub Actions workflow for your Next.js project that ensures all pull requests pass linting, testing, and building checks.

Create this file `.github/workflows/ci.yml`

```yaml
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test

      - name: Build Project
        run: yarn build
```
